# This is a basic workflow to help you get started with Actions

name: Custom Action Demo

# Controls when the workflow will run
on:  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "helloworldaction"
  hello_world_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:    
      # Run hello world javascript action
      - name: Hello world action step
        id: hello
        uses: jaymit-sg/hello-world-javascript-action@main
        with:
          who-to-greet: 'Jaymit'
    
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
